name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  TARGET: wasm32-unknown-unknown

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          rustup target add $TARGET
          cargo build --verbose --target $TARGET
      - name: Run tests
        run: cargo test --verbose